### PR TITLE
Persist nested checkboxes

### PR DESCRIPTION
**Pull request by NSmeef**

### CODE REVIEW

**Comment by jameskirk84** [comment]
Theres a defect with this: If you run the server up in dev mode and select term1AA then search it selects term1B too.  In this case it should select Term1, Term1A, Term1AA

**Comment by NSmeef** [comment]
@jameskirk84 cant replicate in `dev` mode

**Comment by dcmwong** [comment]
just done a pull and can't replicate the bug.  Selected 1AA and apply filters.  Term1, Term1A and Term1AAA are the only ones highlighted

**Comment by NSmeef** [comment]
Managed to replicate however the issue seemed to reside in the stubbed vocab terms in `dev`.

**Pull request merged**
